# Generated by Django 2.1.7 on 2019-02-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0002_auto_20190226_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Username',
            field=models.CharField(default='Username', max_length=10),
        ),
    ]
